// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package internal

import (
	"context"

	"github.com/gofrs/uuid"
)

const insertAlert = `-- name: InsertAlert :exec
insert into alerts (id, fingerprint, alertname) values ($1, $2, $3) on conflict do nothing
`

type InsertAlertParams struct {
	ID          uuid.UUID
	Fingerprint string
	Alertname   string
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.ExecContext(ctx, insertAlert, arg.ID, arg.Fingerprint, arg.Alertname)
	return err
}
