// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package internal

import (
	"context"
)

const placeHolder = `-- name: PlaceHolder :exec
select
  1
`

func (q *Queries) PlaceHolder(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, placeHolder)
	return err
}
